gui:
  showFileTree: false
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - reverse
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: always
    # pager: delta --paging=never --24-bit-color=never --side-by-side
    pager: delta --paging=never --24-bit-color=never

os:
  editCommand: 'floaterm'

keybinding:
  commits:
    moveDownCommit: 'J' # move commit down one
    moveUpCommit: 'K' # move commit up one

promptToReturnFromSubprocess: false

customCommands:
  - key: "S"
    description: "Stash unstaged changes"
    command: "git stash --keep-index"
    context: "files"
  - key: "o"
    description: "Show selected commit"
    command: "git -c delta.paging=always show {{.SelectedLocalCommit.Sha}}"
    context: "commits"
    subprocess: true
