gui:
  sidePanelWidth: 0.22
  showFileTree: false
  showPanelJumps: false
  showBottomLine: false
  border: 'rounded'
  useHunkModeInStagingView: false
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - reverse
    selectedRangeBgColor:
      - underline
git:
  autoFetch: false
  # autoRefresh: false
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --syntax-theme=wave --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      # pager: hunk pager
  log:
    showGraph: never
os:
  edit: '~/.dotfiles/bin/lazygit-edit "{{filename}}"'
  editAtLine: '~/.dotfiles/bin/lazygit-edit "{{filename}}" "{{line}}"'
  editInTerminal: true
  copyToClipboardCmd: 'echo {{text}} | tr -d "\n" | pbcopy'
keybinding:
  universal:
    createPatchOptionsMenu: <c-t>
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-r>"
    description: "Toggle side by side"
    command: "[[ $(git config delta.side-by-side) == \"true\" ]] && git config delta.side-by-side false || git config delta.side-by-side true"
    context: "commits"
    output: terminal
  - key: "M"
    description: "Copy markdown diff"
    command: 'printf "\`\`\`diff\n$(git diff --staged)\n\n\`\`\`" | pbcopy'
    context: "files"
  - key: "Y"
    description: "Send file location to session"
    command: '~/.dotfiles/bin/lazygit-send-note {{.SelectedPath | quote}} {{.SelectedLine.Range.From}} {{.SelectedLine.Range.To}} {{.Form.Note | quote}}'
    context: "staging, stagingSecondary"
    prompts:
      - type: "input"
        key: "Note"
        title: "Note"
  - key: "Y"
    description: "Send commit location to session"
    command: '~/.dotfiles/bin/lazygit-send-note {{.SelectedPath | quote}} {{.SelectedLine.Range.From}} {{.SelectedLine.Range.To}} {{.Form.Note | quote}} {{.SelectedCommit.Hash | quote}}'
    context: "patchBuilding"
    prompts:
      - type: "input"
        key: "Note"
        title: "Note"
