gui:
  sidePanelWidth: 0.22
  showFileTree: false
  showBottomLine: false
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - reverse
    selectedRangeBgColor:
      - underline
git:
  autoFetch: false
  autoRefresh: false
  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never

os:
  editCommand: 'floaterm'

keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'

promptToReturnFromSubprocess: false

customCommands:
  - key: "S"
    description: "Stash unstaged changes"
    command: "git stash --keep-index"
    context: "files"

  - key: "o"
    description: "Show selected commit"
    command: "git show -w {{.SelectedLocalCommit.Sha}}"
    context: "commits"
    subprocess: true

  - key: "<c-r>"
    description: "Toggle side by side"
    command: "[[ $(git config delta.side-by-side) == \"true\" ]] && git config delta.side-by-side false || git config delta.side-by-side true"
    context: "commits"
    subprocess: true
