gui:
  showFileTree: false
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - reverse
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: always
    # pager: delta --paging=never --24-bit-color=never --side-by-side
    pager: delta --paging=never --24-bit-color=never

os:
  editCommand: 'floaterm'

keybinding:
  commits:
    moveDownCommit: 'J' # move commit down one
    moveUpCommit: 'K' # move commit up one

promptToReturnFromSubprocess: false
