gui:
  sidePanelWidth: 0.22
  showFileTree: false
  showPanelJumps: false
  showBottomLine: false
  border: 'rounded'
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - reverse
    selectedRangeBgColor:
      - underline
git:
  # autoFetch: false
  # autoRefresh: false
  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never

os:
  edit: 'floaterm {{filename}} > /dev/null 2>&1 || nvim {{filename}}'
  editAtLine: 'floaterm {{filename}} {{line}} > /dev/null 2>&1 || nvim {{filename}} +{{line}}'
  editInTerminal: true

keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'

promptToReturnFromSubprocess: false

customCommands:
  - key: "<c-r>"
    description: "Toggle side by side"
    command: "[[ $(git config delta.side-by-side) == \"true\" ]] && git config delta.side-by-side false || git config delta.side-by-side true"
    context: "commits"
    subprocess: true
  - key: "b"
    description: "Create new branch from origin/develop"
    command: "git fetch && git checkout origin/develop --no-track -b {{index .PromptResponses 0}}"
    context: "localBranches"
    prompts:
      - type: 'input'
        title: 'New Branch Name:'
  - key: "M"
    description: "Copy markdown diff"
    command: 'printf "\`\`\`diff\n$(git diff --staged)\n\n\`\`\`" | pbcopy'
    context: "files"
