[window]
dynamic_title = false
title = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = false
# PATCH_OPEN
indexed_colors = [
  { index = 244, color = "#25273C"},
  { index = 245, color = "#3E415B"},
  { index = 246, color = "#6D7188"},
  { index = 247, color = "#80859D"},
  { index = 248, color = "#9499B3"},
  { index = 249, color = "#A6ADC9"},
]

[colors.primary]
foreground = '#D4D8ED'
background = '#1C1E2C'

[colors.normal]
black = "#1F2129"
red = "#FF8AA7"
green = "#B2DCCD"
yellow = "#EAD1D1"
blue = "#CCD7BC"
magenta = "#C098FB"
cyan = "#F0A3BE"
white = "#C6CCD7"

[colors.bright]
black = "#5C617A"
red = "#FF5773"
green = "#1BFE9F"
yellow = "#FAE4B3"
blue = "#B88FDC"
magenta = "#FF007B"
cyan = "#89D0D2"
white = "#A2A6C3"
# PATCH_CLOSE

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1B2A"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1B2A"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1B2A"

[colors.selection]
background = "#F5E0DC"
text = "#1E1B2A"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1B2A"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1B2A"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1B2A"

[mouse]
bindings = [
  { mouse = "Middle", action = "None" },
]
