require('andre.cmp')
require('andre.colorizer')
require('andre.harpoon')
require('andre.hop')
require('andre.lsp')
require('andre.lualine')
require('andre.luasnip')
require('andre.nvimtree')
require('andre.octo')
require('andre.telescope')
require('andre.treesitter')
require('andre.autopairs') -- this has to load after cmp
