import = [
  "L:\\home\\andre\\.dotfiles\\systems\\shared\\alacritty.toml",
]

[window]
decorations = "none"
padding = { x = 2, y = 2}

[font]
size = 8.0
offset.x = 0  # For letter spacing (default: 0)
offset.y = 1  # For line spacing (default: 0)

[font.normal]
family = "Operator Mono SSm"
style = "Book"

[font.italic]
style = "Book Italic"

[font.bold]
style = "Medium"

[font.bold_italic]
style = "Medium Italic"

[shell]
program = "C:\\Users\\andre\\AppData\\Local\\Microsoft\\WindowsApps\\ubuntu.exe"

[keyboard]
bindings = [
  { key = "v"        , mods = "Alt"           , action = "Paste" },
  { key = "W"        , mods = "Alt"           , chars = "\u0010\u0078" },
  { key = "J"        , mods = "Alt"           , chars = "\u0010\u005B" },
  { key = "K"        , mods = "Alt"           , chars = "\u0010\u000C" },
  { key = "{"        , mods = "Alt|Shift"     , chars = "\u001B[" },
  { key = "}"        , mods = "Alt|Shift"     , chars = "\u001B]" },
  { key = "["        , mods = "Alt"           , chars = "\u0010P" },
  { key = "]"        , mods = "Alt"           , chars = "\u0010N" },
  { key = "Space"    , mods = "Control"       , chars = "\u0000"     },
  { key = "Return"   , mods = "Alt"           , action = "None"    },
  { key = "Key0"     , mods = "Control"       , chars = "\u0010\u0030" },
  { key = "Key1"     , mods = "Control"       , chars = "\u0010\u0031" },
  { key = "Key2"     , mods = "Control"       , chars = "\u0010\u0032" },
  { key = "Key3"     , mods = "Control"       , chars = "\u0010\u0033" },
  { key = "Key4"     , mods = "Control"       , chars = "\u0010\u0034" },
  { key = "Key5"     , mods = "Control"       , chars = "\u0010\u0035" },
  { key = "Key6"     , mods = "Control"       , chars = "\u0010\u0036" },
  { key = "Key7"     , mods = "Control"       , chars = "\u0010\u0037" },
  { key = "Key8"     , mods = "Control"       , chars = "\u0010\u0038" },
  { key = "Key9"     , mods = "Control"       , chars = "\u0010\u0039" },
  { key = "Slash"    , mods = "Alt"           , chars = ",ct" },
  { key = "Y"        , mods = "Alt"           , chars = ",Hy" },
  { key = "U"        , mods = "Alt"           , chars = ",Hu" },
  { key = "I"        , mods = "Alt"           , chars = ",Hi" },
  { key = "O"        , mods = "Alt"           , chars = ",Ho" },
  { key = "P"        , mods = "Alt"           , chars = ",Hp" },
  { key = "Y"        , mods = "Alt|Shift"     , chars = ",HY" },
  { key = "U"        , mods = "Alt|Shift"     , chars = ",HU" },
  { key = "I"        , mods = "Alt|Shift"     , chars = ",HI" },
  { key = "O"        , mods = "Alt|Shift"     , chars = ",HO" },
  { key = "P"        , mods = "Alt|Shift"     , chars = ",HP" },
  { key = "L"        , mods = "Alt"           , chars = "\u0010z" },
  { key = "F"        , mods = "Alt"           , chars = "]qzz" },
  { key = "D"        , mods = "Alt"           , chars = "[qzz" },

  # { key = "A"        , mods = "Alt"           , chars = "\u001Ba"    },
]
