add_newline = false

format = """$custom$directory$git_branch$git_status$git_state[»](purple) """

[custom.linode]
command = 'echo "[linode]"'
when = 'test `hostname` = "linode"'

[custom.andrembw]
command = 'echo "[andrembw]"'
when = 'test `hostname` = "andrembw.local"'

[directory]
truncation_length = 1000
truncate_to_repo = false

[git_branch]
format = "[<$branch>]($style) "
style = "yellow"

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count} "
stashed = ""
