add_newline = false

format = """$custom$directory$git_branch$git_status$git_state[»](purple) """

[custom.hertzner]
command = 'echo "[dre-ash-1]"'
when = 'test `hostname` = "dre-ash-1"'

# [custom.andrem2]
# command = 'echo "[andrem2]"'
# when = 'test `hostname` = "andrem2.local" || test `hostname` = "andrembw"'

[directory]
truncation_length = 1000
truncate_to_repo = false

[git_branch]
format = "[<$branch>]($style) "
style = "yellow"

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count} "
stashed = ""
