add_newline = false

format = """$directory$git_branch$git_status$git_state[»](purple) """

[directory]
truncation_length = 1000
truncate_to_repo = false

[git_branch]
format = "[<$branch>]($style) "
style = "yellow"

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count} "
stashed = ""
